require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '254742063632',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
   ALIVE_URL: process.env.ALIVE_URL,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoib0YxbEJtS0J3UjR6WHJDZXhnRE9Cc1VmQW9aRXNDQ3RVUlR4RE1oby9GVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS2NrZkNYbU80eHN2NlZFTXVmVGMvK1UxV24rNnhhUkFUUldJYXFLUXBYZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJrR3Z2NlJ1U2JxV1RiYnIrOC9MZjhTbURiZXRsWGx5QkVocVkvYkRwTFVvPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0RUhSaHlFU1daSXVHQVc0a0IvWkw3RTNHaTJ2V0YvU2l6eUdtbUU3cEVZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNLSjgrR3hobnQwOVJLaURvK3pHV2tNT2kvYmt4MzkyUVlmaFRKQnUzWHM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InlmZm03MUFKZzMzYVh2QXluOVRacjFPd0ZxbW14bzF4bmpoYVVEalVNd0E9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYU5Pejg1enExd2RsaGJNNnIxRHo1RXUvM09nM3hQYmxEYk1TOVJydUdWZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiN21Vb0NaSW1hV0pRZUFFZEU1T2ozcTNicUdpL0hvRHhCRGtVWWpJY2JTUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlBVVHVEeHZPV1hDZVV1SnE1cVhVc3JlRzMrV1NIUkdkWGlLb1huTkhid2JZbjZmWXVqVG84aEZVM2E1VEFNOW5GMGNTWWJ6b1NiVS9IdUtLa2Y1ZURnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTM3LCJhZHZTZWNyZXRLZXkiOiJLdkgrWXNERjdzZ3pKNDBDOXJVM3FUeEFFeUFML0hwcm9PeXN2L0YrU1FBPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc0ODE1MjM5NUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI4RkUzMUM3RUNCMkNEQTc4OUM4NTg2OTUzNUVBMTYyRSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUwNTA5NjA3fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJBSllZR1dZNCIsIm1lIjp7ImlkIjoiMjU0NzQ4MTUyMzk1OjhAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIxODU5NzI2NTQzNDYzMzA6OEBsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ01uQTBONENFSkhRMnNJR0dBSWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Ii9Hak1oUmdVVklhbnJ6U3JMUFVlTlFyYVJRNGRQaDVDdVlxU1BnS2o4WE09IiwiYWNjb3VudFNpZ25hdHVyZSI6ImtaWnhiMk91eWY1S21KcTU1NUdQTUJoZEp0L2gwQU9QeXFaQ3JpUElJYmo5enFoYjRrbEJlWWVabU9JWmlrN2NERjc1WTc1Z1JLVjh6aEs3RUFYdkRBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiIxY0VrUmc3SWowek05ZzlHUE9pYVZFam1raGhBQWJ6TkR4OXZhVmZTYThWajNkamlWcGFXU2VCYlVoekQ0L3F4MTRmekFVUWJXQ2JRTmhkRFpma2tEdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDc0ODE1MjM5NTo4QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmZ4b3pJVVlGRlNHcDY4MHF5ejFIalVLMmtVT0hUNGVRcm1La2o0Q28vRnoifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBZ0lCUT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc1MDUwOTU5OSwibGFzdFByb3BIYXNoIjoiMlY3N3FVIiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFITXEifQ==',
    timezone: 'Africa/Nairobi',
    USER_LID: process.env.YOUR_LID || null,
    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
